# TODO: Replace with terraform code
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: nexus
spec:
  serviceName: nexus-repository2
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nexus-repository2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus-repository2
    spec:
      containers:
      - image: eu.gcr.io/cw-data-test/nexus-repository-apt:latest
        imagePullPolicy: Always
        name: nexus-repository-apt
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nexus-storage
          mountPath: /nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: nexus-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
